namespace BD2SecretVision;
public readonly record struct Point(int X,int Y);
public sealed record Node(int X,int Y,bool Claim=false,double WaitBeforeS=0);
public sealed class Player {public int X{get;set;}public int Y{get;set;}public double U{get;set;}public double V{get;set;}public double Speed{get;set;}public double Radius{get;set;}=32;public int SpeedStacks{get;set;}public int SlowStacks{get;set;}public double SuperBonus{get;set;}public double SuperRemaining{get;set;}public bool Drawing{get;set;}public bool Closing{get;set;}public Point Point=>new(X,Y);}
public sealed class Enemy {public string Monster{get;set;}="";public string State{get;set;}="";public double[] Position{get;set;}=[0,0];public double NormalInterval{get;set;}public double NormalElapsed{get;set;}public double SpecialInterval{get;set;}public double SpecialElapsed{get;set;}public double ControlRemaining{get;set;}public string CarveState{get;set;}="None";public bool CarveReadyInterrupted{get;set;}public double CarveBlockedRemaining{get;set;}}
public sealed class Body {public double[] Position{get;set;}=[0,0];public double[] Velocity{get;set;}=[0,0];public double[] MotionVelocity{get;set;}=[0,0];public double MotionHorizon{get;set;}public double Radius{get;set;}public double SpeedBound{get;set;}public double FrozenRemaining{get;set;}}
public sealed class Item {public string Type{get;set;}="";public double[] Position{get;set;}=[0,0];public bool Collected{get;set;}public double Remaining{get;set;}}
public sealed class Board {public int Id{get;set;}public string State{get;set;}="";public int Width{get;set;}public int Height{get;set;}public double CellSize{get;set;}public double Percent{get;set;}public double Remaining{get;set;}public bool Continued{get;set;}public string[] Rows{get;set;}=[];public string[] HorizontalEdges{get;set;}=[];public string[] VerticalEdges{get;set;}=[];public string TopologyKey{get;set;}="";public bool HasTopology=>HorizontalEdges.Length==Height+1&&VerticalEdges.Length==Height;public Player Player{get;set;}=new();public Enemy Enemy{get;set;}=new();public Body[] Bodies{get;set;}=[];public Body[] Projectiles{get;set;}=[];public Item[] Items{get;set;}=[];public bool Claimed(int x,int y)=>x>=0&&y>=0&&x<Width&&y<Height&&Rows[y][x]=='C';public bool Finished=>State is "End" or "Over";}
public sealed class Ui {public string Type{get;set;}="";public string[] Texts{get;set;}=[];}
public sealed class Snapshot {public int Protocol{get;set;}public int Pid{get;set;}public long ProcessStart{get;set;}public string Session{get;set;}="";public DateTimeOffset AtUtc{get;set;}public string Round{get;set;}="";public int Stage{get;set;}public bool Running{get;set;}public string Reason{get;set;}="";public int Cursor{get;set;}public int Count{get;set;}public Board? Board{get;set;}public Ui[] UIs{get;set;}=[];}
public sealed class Progress {public string Status{get;set;}="idle";public int Stage{get;set;}public int Attempt{get;set;}public List<int> Cleared{get;set;}=[];public double Percent{get;set;}public double Remaining{get;set;}public string Detail{get;set;}="";public string Warning{get;set;}="";public string Output{get;set;}="";}
public sealed class Settings {public int[] Stages{get;set;}=[1];public bool Retry{get;set;}=true;public int TargetPercent{get;set;}=100;public int MaxAttempts{get;set;}=0;
 public void Validate(){if(Stages.Length==0||Stages.Distinct().Count()!=Stages.Length||Stages.Any(s=>s<1||s>5))throw new ArgumentException("invalid-stages");if(TargetPercent!=80&&TargetPercent!=100)throw new ArgumentException("invalid-target");if(MaxAttempts<0||MaxAttempts>1000)throw new ArgumentException("invalid-attempts");}
}
public sealed class RouteFailure(string message):Exception(message);
